import { getRequestConfig } from "next-intl/server";
import { hasLocale } from "next-intl";
import { routing } from "@/i18n/routing";

/**
 * Per-request i18n config for Server Components/Server Actions (see
 * docs/I18N_PLAN.md §3).
 *
 * Uses the `requestLocale` parameter (populated from the `x-next-intl-locale`
 * header that `next-intl`'s middleware attaches to the request — see
 * next-intl's "Request configuration" docs) rather than `next/root-params`.
 * `next/root-params`'s named per-segment exports (e.g. `locale()`) are NOT
 * generated by Turbopack as of Next.js 16.3 — this is a confirmed, currently
 * open Next.js bug (github.com/vercel/next.js/issues/92742, "[Turbopack]
 * rootParams: next/root-params exports not generated by compiler"), which
 * makes `import * as rootParams from "next/root-params"` fail the production
 * build with "Export locale doesn't exist in target module". `requestLocale`
 * is the still-fully-supported, non-experimental alternative and pairs with
 * the `setRequestLocale(locale)` call already present in
 * `app/[locale]/layout.tsx` to keep static rendering working.
 *
 * `/admin/**` deliberately lives OUTSIDE the `[locale]` segment (see
 * docs/I18N_PLAN.md §2 — back-office stays English-only by design), and
 * `proxy.ts` deliberately skips next-intl's middleware for `/admin/**`, so
 * no `x-next-intl-locale` header is ever set for those requests —
 * `requestLocale` legitimately resolves to `undefined` there. This must
 * fall back to `routing.defaultLocale`, NOT call `notFound()` — the shared
 * root layout (`app/layout.tsx`) calls `getLocale()` (which goes through
 * this same config) on every request including `/admin/**`, so a `notFound()`
 * here would break every admin page, not just report a legitimately-missing
 * locale segment.
 */
export default getRequestConfig(async ({ requestLocale }) => {
  const requested = await requestLocale;
  const locale = hasLocale(routing.locales, requested) ? requested : routing.defaultLocale;

  return {
    locale,
    messages: (await import(`../messages/${locale}.json`)).default,
    timeZone: "Asia/Dhaka",
  };
});
